package colf;


// This file was generated by colf(1); DO NOT EDIT
// The compiler used schema file RpcDTO.colfer.


import static java.lang.String.format;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.util.InputMismatchException;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;



/**
 * Data bean with built-in serialization support.
 * @author generated by colf(1)
 * @see <a href="https://github.com/pascaldekloe/colfer">Colfer's home</a>
 */
public class Request

  implements java.io.Serializable {

	/** The upper limit for serial byte sizes. */
	public static int colferSizeMax = 16 * 1024 * 1024;

	/** The upper limit for the number of elements in a list. */
	public static int colferListMax = 64 * 1024;

	private static final byte[] _zeroBytes = new byte[0];
	private static final byte[][] _zeroBinaries = new byte[0][];
	private static final Attachment[] _zeroAttachments = new Attachment[0];


	public String interfaceName = "";

	public String methodName = "";

	public String paramtersDesc = "";

	public byte[][] arguments = _zeroBinaries;

	public Attachment[] attachments = _zeroAttachments;


	/**
	 * {@link #reset(InputStream) Reusable} deserialization of Colfer streams.
	 */
	public static class Unmarshaller {

		/** The data source. */
		protected InputStream in;

		/** The read buffer. */
		public byte[] buf;

		/** The {@link #buf buffer}'s data start index, inclusive. */
		protected int offset;

		/** The {@link #buf buffer}'s data end index, exclusive. */
		protected int i;


		/**
		 * @param in the data source or {@code null}.
		 * @param buf the initial buffer or {@code null}.
		 */
		public Unmarshaller(InputStream in, byte[] buf) {
			if (buf == null || buf.length == 0)
				buf = new byte[Math.min(Request.colferSizeMax, 2048)];
			this.buf = buf;
			reset(in);
		}

		/**
		 * Reuses the marshaller.
		 * @param in the data source or {@code null}.
		 * @throws IllegalStateException on pending data.
		 */
		public void reset(InputStream in) {
			if (this.i != this.offset) throw new IllegalStateException("colfer: pending data");
			this.in = in;
			this.offset = 0;
			this.i = 0;
		}

		/**
		 * Deserializes the following object.
		 * @return the result or {@code null} when EOF.
		 * @throws IOException from the input stream.
		 * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
		 * @throws InputMismatchException when the data does not match this object's schema.
		 */
		public Request next() throws IOException {
			if (in == null) return null;

			while (true) {
				if (this.i > this.offset) {
					try {
						Request o = new Request();
						this.offset = o.unmarshal(this.buf, this.offset, this.i);
						return o;
					} catch (BufferUnderflowException e) {
					}
				}
				// not enough data

				if (this.i <= this.offset) {
					this.offset = 0;
					this.i = 0;
				} else if (i == buf.length) {
					byte[] src = this.buf;
					if (offset == 0) this.buf = new byte[Math.min(Request.colferSizeMax, this.buf.length * 4)];
					System.arraycopy(src, this.offset, this.buf, 0, this.i - this.offset);
					this.i -= this.offset;
					this.offset = 0;
				}
				assert this.i < this.buf.length;

				int n = in.read(buf, i, buf.length - i);
				if (n < 0) {
					if (this.i > this.offset)
						throw new InputMismatchException("colfer: pending data with EOF");
					return null;
				}
				assert n > 0;
				i += n;
			}
		}

	}


	/**
	 * Serializes the object.
	 * All {@code null} elements in {@link #arguments} will be replaced with an empty byte array.
	 * All {@code null} elements in {@link #attachments} will be replaced with a {@code new} value.
	 * @param out the data destination.
	 * @param buf the initial buffer or {@code null}.
	 * @return the final buffer. When the serial fits into {@code buf} then the return is {@code buf}.
	 *  Otherwise the return is a new buffer, large enough to hold the whole serial.
	 * @throws IOException from {@code out}.
	 * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
	 */
	public byte[] marshal(OutputStream out, byte[] buf) throws IOException {
		if (buf == null || buf.length == 0)
			buf = new byte[Math.min(Request.colferSizeMax, 2048)];

		while (true) {
			int i;
			try {
				i = marshal(buf, 0);
			} catch (BufferOverflowException e) {
				buf = new byte[Math.min(Request.colferSizeMax, buf.length * 4)];
				continue;
			}

			out.write(buf, 0, i);
			return buf;
		}
	}

	/**
	 * Serializes the object.
	 * All {@code null} elements in {@link #arguments} will be replaced with an empty byte array.
	 * All {@code null} elements in {@link #attachments} will be replaced with a {@code new} value.
	 * @param buf the data destination.
	 * @param offset the initial index for {@code buf}, inclusive.
	 * @return the final index for {@code buf}, exclusive.
	 * @throws BufferOverflowException when {@code buf} is too small.
	 * @throws IllegalStateException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
	 */
	public int marshal(byte[] buf, int offset) {
		int i = offset;

		try {
			if (! this.interfaceName.isEmpty()) {
				buf[i++] = (byte) 0;
				int start = ++i;

				String s = this.interfaceName;
				for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
					char c = s.charAt(sIndex);
					if (c < '\u0080') {
						buf[i++] = (byte) c;
					} else if (c < '\u0800') {
						buf[i++] = (byte) (192 | c >>> 6);
						buf[i++] = (byte) (128 | c & 63);
					} else if (c < '\ud800' || c > '\udfff') {
						buf[i++] = (byte) (224 | c >>> 12);
						buf[i++] = (byte) (128 | c >>> 6 & 63);
						buf[i++] = (byte) (128 | c & 63);
					} else {
						int cp = 0;
						if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
						if ((cp >= 1 << 16) && (cp < 1 << 21)) {
							buf[i++] = (byte) (240 | cp >>> 18);
							buf[i++] = (byte) (128 | cp >>> 12 & 63);
							buf[i++] = (byte) (128 | cp >>> 6 & 63);
							buf[i++] = (byte) (128 | cp & 63);
						} else
							buf[i++] = (byte) '?';
					}
				}
				int size = i - start;
				if (size > Request.colferSizeMax)
					throw new IllegalStateException(format("colfer: colf.Request.interfaceName size %d exceeds %d UTF-8 bytes", size, Request.colferSizeMax));

				int ii = start - 1;
				if (size > 0x7f) {
					i++;
					for (int x = size; x >= 1 << 14; x >>>= 7) i++;
					System.arraycopy(buf, start, buf, i - size, size);

					do {
						buf[ii++] = (byte) (size | 0x80);
						size >>>= 7;
					} while (size > 0x7f);
				}
				buf[ii] = (byte) size;
			}

			if (! this.methodName.isEmpty()) {
				buf[i++] = (byte) 1;
				int start = ++i;

				String s = this.methodName;
				for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
					char c = s.charAt(sIndex);
					if (c < '\u0080') {
						buf[i++] = (byte) c;
					} else if (c < '\u0800') {
						buf[i++] = (byte) (192 | c >>> 6);
						buf[i++] = (byte) (128 | c & 63);
					} else if (c < '\ud800' || c > '\udfff') {
						buf[i++] = (byte) (224 | c >>> 12);
						buf[i++] = (byte) (128 | c >>> 6 & 63);
						buf[i++] = (byte) (128 | c & 63);
					} else {
						int cp = 0;
						if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
						if ((cp >= 1 << 16) && (cp < 1 << 21)) {
							buf[i++] = (byte) (240 | cp >>> 18);
							buf[i++] = (byte) (128 | cp >>> 12 & 63);
							buf[i++] = (byte) (128 | cp >>> 6 & 63);
							buf[i++] = (byte) (128 | cp & 63);
						} else
							buf[i++] = (byte) '?';
					}
				}
				int size = i - start;
				if (size > Request.colferSizeMax)
					throw new IllegalStateException(format("colfer: colf.Request.methodName size %d exceeds %d UTF-8 bytes", size, Request.colferSizeMax));

				int ii = start - 1;
				if (size > 0x7f) {
					i++;
					for (int x = size; x >= 1 << 14; x >>>= 7) i++;
					System.arraycopy(buf, start, buf, i - size, size);

					do {
						buf[ii++] = (byte) (size | 0x80);
						size >>>= 7;
					} while (size > 0x7f);
				}
				buf[ii] = (byte) size;
			}

			if (! this.paramtersDesc.isEmpty()) {
				buf[i++] = (byte) 2;
				int start = ++i;

				String s = this.paramtersDesc;
				for (int sIndex = 0, sLength = s.length(); sIndex < sLength; sIndex++) {
					char c = s.charAt(sIndex);
					if (c < '\u0080') {
						buf[i++] = (byte) c;
					} else if (c < '\u0800') {
						buf[i++] = (byte) (192 | c >>> 6);
						buf[i++] = (byte) (128 | c & 63);
					} else if (c < '\ud800' || c > '\udfff') {
						buf[i++] = (byte) (224 | c >>> 12);
						buf[i++] = (byte) (128 | c >>> 6 & 63);
						buf[i++] = (byte) (128 | c & 63);
					} else {
						int cp = 0;
						if (++sIndex < sLength) cp = Character.toCodePoint(c, s.charAt(sIndex));
						if ((cp >= 1 << 16) && (cp < 1 << 21)) {
							buf[i++] = (byte) (240 | cp >>> 18);
							buf[i++] = (byte) (128 | cp >>> 12 & 63);
							buf[i++] = (byte) (128 | cp >>> 6 & 63);
							buf[i++] = (byte) (128 | cp & 63);
						} else
							buf[i++] = (byte) '?';
					}
				}
				int size = i - start;
				if (size > Request.colferSizeMax)
					throw new IllegalStateException(format("colfer: colf.Request.paramtersDesc size %d exceeds %d UTF-8 bytes", size, Request.colferSizeMax));

				int ii = start - 1;
				if (size > 0x7f) {
					i++;
					for (int x = size; x >= 1 << 14; x >>>= 7) i++;
					System.arraycopy(buf, start, buf, i - size, size);

					do {
						buf[ii++] = (byte) (size | 0x80);
						size >>>= 7;
					} while (size > 0x7f);
				}
				buf[ii] = (byte) size;
			}

			if (this.arguments.length != 0) {
				buf[i++] = (byte) 3;
				byte[][] a = this.arguments;

				int x = a.length;
				if (x > Request.colferListMax)
					throw new IllegalStateException(format("colfer: colf.Request.arguments length %d exceeds %d elements", x, Request.colferListMax));
				while (x > 0x7f) {
					buf[i++] = (byte) (x | 0x80);
					x >>>= 7;
				}
				buf[i++] = (byte) x;

				for (int ai = 0; ai < a.length; ai++) {
					byte[] b = a[ai];
					if (b == null) {
						b = _zeroBytes;
						a[ai] = b;
					}
					if (b.length > Request.colferSizeMax)
						throw new IllegalStateException(format("colfer: colf.Request.arguments[%d] size %d exceeds %d bytes", ai, b.length, Request.colferSizeMax));

					x = b.length;
					while (x > 0x7f) {
						buf[i++] = (byte) (x | 0x80);
						x >>>= 7;
					}
					buf[i++] = (byte) x;

					int start = i;
					i += b.length;
					System.arraycopy(b, 0, buf, start, b.length);
				}
			}

			if (this.attachments.length != 0) {
				buf[i++] = (byte) 4;
				Attachment[] a = this.attachments;

				int x = a.length;
				if (x > Request.colferListMax)
					throw new IllegalStateException(format("colfer: colf.Request.attachments length %d exceeds %d elements", x, Request.colferListMax));
				while (x > 0x7f) {
					buf[i++] = (byte) (x | 0x80);
					x >>>= 7;
				}
				buf[i++] = (byte) x;

				for (int ai = 0; ai < a.length; ai++) {
					Attachment o = a[ai];
					if (o == null) {
						o = new Attachment();
						a[ai] = o;
					}
					i = o.marshal(buf, i);
				}
			}

			buf[i++] = (byte) 0x7f;
			return i;
		} catch (ArrayIndexOutOfBoundsException e) {
			if (i - offset > Request.colferSizeMax)
				throw new IllegalStateException(format("colfer: colf.Request exceeds %d bytes", Request.colferSizeMax));
			if (i > buf.length) throw new BufferOverflowException();
			throw e;
		}
	}

	/**
	 * Deserializes the object.
	 * @param buf the data source.
	 * @param offset the initial index for {@code buf}, inclusive.
	 * @return the final index for {@code buf}, exclusive.
	 * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
	 * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
	 * @throws InputMismatchException when the data does not match this object's schema.
	 */
	public int unmarshal(byte[] buf, int offset) {
		return unmarshal(buf, offset, buf.length);
	}

	/**
	 * Deserializes the object.
	 * @param buf the data source.
	 * @param offset the initial index for {@code buf}, inclusive.
	 * @param end the index limit for {@code buf}, exclusive.
	 * @return the final index for {@code buf}, exclusive.
	 * @throws BufferUnderflowException when {@code buf} is incomplete. (EOF)
	 * @throws SecurityException on an upper limit breach defined by either {@link #colferSizeMax} or {@link #colferListMax}.
	 * @throws InputMismatchException when the data does not match this object's schema.
	 */
	public int unmarshal(byte[] buf, int offset, int end) {
		if (end > buf.length) end = buf.length;
		int i = offset;

		try {
			byte header = buf[i++];

			if (header == (byte) 0) {
				int size = 0;
				for (int shift = 0; true; shift += 7) {
					byte b = buf[i++];
					size |= (b & 0x7f) << shift;
					if (shift == 28 || b >= 0) break;
				}
				if (size < 0 || size > Request.colferSizeMax)
					throw new SecurityException(format("colfer: colf.Request.interfaceName size %d exceeds %d UTF-8 bytes", size, Request.colferSizeMax));

				int start = i;
				i += size;
				this.interfaceName = new String(buf, start, size, StandardCharsets.UTF_8);
				header = buf[i++];
			}

			if (header == (byte) 1) {
				int size = 0;
				for (int shift = 0; true; shift += 7) {
					byte b = buf[i++];
					size |= (b & 0x7f) << shift;
					if (shift == 28 || b >= 0) break;
				}
				if (size < 0 || size > Request.colferSizeMax)
					throw new SecurityException(format("colfer: colf.Request.methodName size %d exceeds %d UTF-8 bytes", size, Request.colferSizeMax));

				int start = i;
				i += size;
				this.methodName = new String(buf, start, size, StandardCharsets.UTF_8);
				header = buf[i++];
			}

			if (header == (byte) 2) {
				int size = 0;
				for (int shift = 0; true; shift += 7) {
					byte b = buf[i++];
					size |= (b & 0x7f) << shift;
					if (shift == 28 || b >= 0) break;
				}
				if (size < 0 || size > Request.colferSizeMax)
					throw new SecurityException(format("colfer: colf.Request.paramtersDesc size %d exceeds %d UTF-8 bytes", size, Request.colferSizeMax));

				int start = i;
				i += size;
				this.paramtersDesc = new String(buf, start, size, StandardCharsets.UTF_8);
				header = buf[i++];
			}

			if (header == (byte) 3) {
				int length = 0;
				for (int shift = 0; true; shift += 7) {
					byte b = buf[i++];
					length |= (b & 0x7f) << shift;
					if (shift == 28 || b >= 0) break;
				}
				if (length < 0 || length > Request.colferListMax)
					throw new SecurityException(format("colfer: colf.Request.arguments length %d exceeds %d elements", length, Request.colferListMax));

				byte[][] a = new byte[length][];
				for (int ai = 0; ai < length; ai++) {
					int size = 0;
					for (int shift = 0; true; shift += 7) {
						byte b = buf[i++];
						size |= (b & 0x7f) << shift;
						if (shift == 28 || b >= 0) break;
					}
					if (size < 0 || size > Request.colferSizeMax)
						throw new SecurityException(format("colfer: colf.Request.arguments[%d] size %d exceeds %d bytes", ai, size, Request.colferSizeMax));

					byte[] e = new byte[size];
					int start = i;
					i += size;
					System.arraycopy(buf, start, e, 0, size);
					a[ai] = e;
				}
				this.arguments = a;
				header = buf[i++];
			}

			if (header == (byte) 4) {
				int length = 0;
				for (int shift = 0; true; shift += 7) {
					byte b = buf[i++];
					length |= (b & 0x7f) << shift;
					if (shift == 28 || b >= 0) break;
				}
				if (length < 0 || length > Request.colferListMax)
					throw new SecurityException(format("colfer: colf.Request.attachments length %d exceeds %d elements", length, Request.colferListMax));

				Attachment[] a = new Attachment[length];
				for (int ai = 0; ai < length; ai++) {
					Attachment o = new Attachment();
					i = o.unmarshal(buf, i, end);
					a[ai] = o;
				}
				this.attachments = a;
				header = buf[i++];
			}

			if (header != (byte) 0x7f)
				throw new InputMismatchException(format("colfer: unknown header at byte %d", i - 1));
		} finally {
			if (i > end && end - offset < Request.colferSizeMax) throw new BufferUnderflowException();
			if (i < 0 || i - offset > Request.colferSizeMax)
				throw new SecurityException(format("colfer: colf.Request exceeds %d bytes", Request.colferSizeMax));
			if (i > end) throw new BufferUnderflowException();
		}

		return i;
	}

	/**
	 * Gets colf.Request.interfaceName.
	 * @return the value.
	 */
	public String getInterfaceName() {
		return this.interfaceName;
	}

	/**
	 * Sets colf.Request.interfaceName.
	 * @param value the replacement.
	 */
	public void setInterfaceName(String value) {
		this.interfaceName = value;
	}

	/**
	 * Gets colf.Request.methodName.
	 * @return the value.
	 */
	public String getMethodName() {
		return this.methodName;
	}

	/**
	 * Sets colf.Request.methodName.
	 * @param value the replacement.
	 */
	public void setMethodName(String value) {
		this.methodName = value;
	}

	/**
	 * Gets colf.Request.paramtersDesc.
	 * @return the value.
	 */
	public String getParamtersDesc() {
		return this.paramtersDesc;
	}

	/**
	 * Sets colf.Request.paramtersDesc.
	 * @param value the replacement.
	 */
	public void setParamtersDesc(String value) {
		this.paramtersDesc = value;
	}

	/**
	 * Gets colf.Request.arguments.
	 * @return the value.
	 */
	public byte[][] getArguments() {
		return this.arguments;
	}

	/**
	 * Sets colf.Request.arguments.
	 * @param value the replacement.
	 */
	public void setArguments(byte[][] value) {
		this.arguments = value;
	}

	/**
	 * Gets colf.Request.attachments.
	 * @return the value.
	 */
	public Attachment[] getAttachments() {
		return this.attachments;
	}

	/**
	 * Sets colf.Request.attachments.
	 * @param value the replacement.
	 */
	public void setAttachments(Attachment[] value) {
		this.attachments = value;
	}

	@Override
	public final int hashCode() {
		int h = 1;
		if (this.interfaceName != null) h = 31 * h + this.interfaceName.hashCode();
		if (this.methodName != null) h = 31 * h + this.methodName.hashCode();
		if (this.paramtersDesc != null) h = 31 * h + this.paramtersDesc.hashCode();
		for (byte[] b : this.arguments) h = 31 * h + java.util.Arrays.hashCode(b);
		for (Attachment o : this.attachments) h = 31 * h + (o == null ? 0 : o.hashCode());
		return h;
	}

	@Override
	public final boolean equals(Object o) {
		return o instanceof Request && equals((Request) o);
	}

	public final boolean equals(Request o) {
		if (o == null) return false;
		if (o == this) return true;
		return o.getClass() == Request.class
			&& this.interfaceName == null ? o.interfaceName == null : this.interfaceName.equals(o.interfaceName)
			&& this.methodName == null ? o.methodName == null : this.methodName.equals(o.methodName)
			&& this.paramtersDesc == null ? o.paramtersDesc == null : this.paramtersDesc.equals(o.paramtersDesc)
			&& _equals(this.arguments, o.arguments)
			&& java.util.Arrays.equals(this.attachments, o.attachments);
	}

	private static boolean _equals(byte[][] a, byte[][] b) {
		if (a == b) return true;
		if (a == null || b == null) return false;

		int i = a.length;
		if (i != b.length) return false;

		while (--i >= 0) if (! java.util.Arrays.equals(a[i], b[i])) return false;
		return true;
	}

}
